// Auto-generated by design-token-gen. Do not edit manually.
import SwiftUI

enum AnimusTheme {
    static let accent = Color(red: 0.270588, green: 0.929412, blue: 0.764706)
    static let accentForeground = Color(red: 0.000000, green: 0.050980, blue: 0.101961)
    static let background = Color(red: 0.007843, green: 0.023529, blue: 0.050980)
    static let border = Color(red: 0.145098, green: 0.192157, blue: 0.254902)
    static let card = Color(red: 0.019608, green: 0.043137, blue: 0.082353)
    static let cardForeground = Color(red: 1.000000, green: 1.000000, blue: 1.000000)
    static let destructive = Color(red: 0.960784, green: 0.278431, blue: 0.278431)
    static let destructiveForeground = Color(red: 0.972549, green: 0.980392, blue: 0.988235)
    static let foreground = Color(red: 0.941176, green: 0.972549, blue: 1.000000)
    static let input = Color(red: 0.145098, green: 0.192157, blue: 0.254902)
    static let muted = Color(red: 0.109804, green: 0.149020, blue: 0.188235)
    static let mutedForeground = Color(red: 0.650980, green: 0.705882, blue: 0.788235)
    static let popover = Color(red: 0.015686, green: 0.035294, blue: 0.066667)
    static let popoverForeground = Color(red: 0.921569, green: 0.956863, blue: 1.000000)
    static let primary = Color(red: 0.274510, green: 0.643137, blue: 0.945098)
    static let primaryForeground = Color(red: 0.960784, green: 0.980392, blue: 1.000000)
    static let ring = Color(red: 0.274510, green: 0.643137, blue: 0.945098)
    static let secondary = Color(red: 0.250980, green: 0.674510, blue: 0.866667)
    static let secondaryForeground = Color(red: 0.921569, green: 0.960784, blue: 1.000000)

    static let radiusRadius: String = "0.8rem"


    static let fontSans: String = "'Space Grotesk', Inter, system-ui, sans-serif"
    static let fontMono: String = "'JetBrains Mono', ui-monospace, SFMono-Regular, monospace"
    static let fontMetricMono: String = "ui-monospace, 'SF Mono', 'Roboto Mono', 'Menlo', 'Consolas', 'Liberation Mono', 'JetBrains Mono', monospace"
}
