/* Auto-generated by design-token-gen. Do not edit manually. */
export const designTokens = {
  "colors": {
    "accent": "165 82% 60%",
    "accent-foreground": "210 100% 5%",
    "background": "217 68% 3%",
    "border": "215 27% 20%",
    "card": "217 63% 5%",
    "card-foreground": "0 0% 100%",
    "destructive": "0 90% 62%",
    "destructive-foreground": "210 40% 98%",
    "foreground": "208 100% 97%",
    "input": "215 27% 20%",
    "muted": "212 26% 15%",
    "muted-foreground": "216 24% 72%",
    "popover": "217 63% 4%",
    "popover-foreground": "213 100% 96%",
    "primary": "207 86% 61%",
    "primary-foreground": "210 100% 98%",
    "ring": "207 86% 61%",
    "secondary": "199 70% 56%",
    "secondary-foreground": "210 100% 96%"
  },
  "radii": {
    "radius": "0.8rem"
  },
  "spacing": {},
  "typography": {
    "font_sans": "'Space Grotesk', Inter, system-ui, sans-serif",
    "font_mono": "'JetBrains Mono', ui-monospace, SFMono-Regular, monospace",
    "font_metric_mono": "ui-monospace, 'SF Mono', 'Roboto Mono', 'Menlo', 'Consolas', 'Liberation Mono', 'JetBrains Mono', monospace",
    "sizes": {}
  }
} as const;
