// Auto-generated by design-token-gen. Do not edit manually.
package com.animus.link.ui

object AnimusTheme {
    const val ACCENT: Long = 0xFF45EDC3L
    const val ACCENT_FOREGROUND: Long = 0xFF000D1AL
    const val BACKGROUND: Long = 0xFF02060DL
    const val BORDER: Long = 0xFF253141L
    const val CARD: Long = 0xFF050B15L
    const val CARD_FOREGROUND: Long = 0xFFFFFFFFL
    const val DESTRUCTIVE: Long = 0xFFF54747L
    const val DESTRUCTIVE_FOREGROUND: Long = 0xFFF8FAFCL
    const val FOREGROUND: Long = 0xFFF0F8FFL
    const val INPUT: Long = 0xFF253141L
    const val MUTED: Long = 0xFF1C2630L
    const val MUTED_FOREGROUND: Long = 0xFFA6B4C9L
    const val POPOVER: Long = 0xFF040911L
    const val POPOVER_FOREGROUND: Long = 0xFFEBF4FFL
    const val PRIMARY: Long = 0xFF46A4F1L
    const val PRIMARY_FOREGROUND: Long = 0xFFF5FAFFL
    const val RING: Long = 0xFF46A4F1L
    const val SECONDARY: Long = 0xFF40ACDDL
    const val SECONDARY_FOREGROUND: Long = 0xFFEBF5FFL

    const val RADIUS_RADIUS: String = "0.8rem"


    const val FONT_SANS: String = "'Space Grotesk', Inter, system-ui, sans-serif"
    const val FONT_MONO: String = "'JetBrains Mono', ui-monospace, SFMono-Regular, monospace"
    const val FONT_METRIC_MONO: String = "ui-monospace, 'SF Mono', 'Roboto Mono', 'Menlo', 'Consolas', 'Liberation Mono', 'JetBrains Mono', monospace"
}
