use std::{
    collections::BTreeMap,
    fs,
    path::{Path, PathBuf},
};

use anyhow::{anyhow, Context, Result};
use serde::{Deserialize, Serialize};

const TOKENS_PATH: &str = "design/tokens.json";
const WEB_CSS_OUT: &str = "packages/ui-web/tailwind.tokens.css";
const WEB_TS_OUT: &str = "packages/ui-web/tokens.ts";
const ANDROID_OUT: &str = "mobile/android/app/src/main/java/com/animus/link/ui/Theme.kt";
const IOS_OUT: &str = "mobile/ios/AnimusLinkIOS/Theme.swift";

#[derive(Debug, Deserialize, Serialize)]
struct Tokens {
    colors: BTreeMap<String, String>,
    radii: BTreeMap<String, String>,
    spacing: BTreeMap<String, String>,
    typography: Typography,
}

#[derive(Debug, Deserialize, Serialize)]
struct Typography {
    font_sans: String,
    font_mono: String,
    #[serde(default)]
    font_metric_mono: Option<String>,
    #[serde(default)]
    sizes: BTreeMap<String, String>,
}

fn main() -> Result<()> {
    let repo_root = PathBuf::from(
        std::env::var("CARGO_MANIFEST_DIR")
            .context("CARGO_MANIFEST_DIR must be set")?
            .trim_end_matches("apps/design-token-gen"),
    );
    let repo_root = repo_root
        .canonicalize()
        .context("failed to canonicalize repository root")?;

    let tokens = read_tokens(&repo_root.join(TOKENS_PATH))?;

    write_out(
        &repo_root.join(WEB_CSS_OUT),
        &render_web_css(&tokens),
        "web css tokens",
    )?;
    write_out(
        &repo_root.join(WEB_TS_OUT),
        &render_web_ts(&tokens),
        "web ts tokens",
    )?;
    write_out(
        &repo_root.join(ANDROID_OUT),
        &render_android_theme(&tokens)?,
        "android theme tokens",
    )?;
    write_out(
        &repo_root.join(IOS_OUT),
        &render_ios_theme(&tokens)?,
        "ios theme tokens",
    )?;

    Ok(())
}

fn read_tokens(path: &Path) -> Result<Tokens> {
    let raw =
        fs::read_to_string(path).with_context(|| format!("failed to read {}", path.display()))?;
    let tokens: Tokens = serde_json::from_str(&raw)
        .with_context(|| format!("failed to parse {}", path.display()))?;
    Ok(tokens)
}

fn write_out(path: &Path, content: &str, label: &str) -> Result<()> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)
            .with_context(|| format!("failed to create parent dir for {}", path.display()))?;
    }
    fs::write(path, content)
        .with_context(|| format!("failed to write {label} to {}", path.display()))
}

fn render_web_css(tokens: &Tokens) -> String {
    let mut out = String::new();
    out.push_str("/* Auto-generated by design-token-gen. Do not edit manually. */\n");
    out.push_str(":root {\n");
    for (name, value) in &tokens.colors {
        out.push_str(format!("  --{name}: {value};\n").as_str());
        out.push_str(format!("  --color-{name}: {value};\n").as_str());
    }
    for (name, value) in &tokens.radii {
        if name == "radius" {
            out.push_str(format!("  --radius: {value};\n").as_str());
            out.push_str(format!("  --radius-{name}: {value};\n").as_str());
        } else {
            out.push_str(format!("  --radius-{name}: {value};\n").as_str());
        }
    }
    for (name, value) in sorted_spacing(&tokens.spacing) {
        out.push_str(format!("  --space-{name}: {value};\n").as_str());
    }
    for (name, value) in &tokens.typography.sizes {
        out.push_str(format!("  --font-size-{name}: {value};\n").as_str());
    }
    out.push_str(format!("  --font-sans: {};\n", tokens.typography.font_sans).as_str());
    out.push_str(format!("  --font-mono: {};\n", tokens.typography.font_mono).as_str());
    if let Some(font_metric_mono) = tokens.typography.font_metric_mono.as_deref() {
        out.push_str(format!("  --font-metric-mono: {};\n", font_metric_mono).as_str());
    }
    out.push_str("}\n");
    out
}

fn render_web_ts(tokens: &Tokens) -> String {
    let json = serde_json::to_string_pretty(tokens).expect("tokens serialization must succeed");
    format!(
        "/* Auto-generated by design-token-gen. Do not edit manually. */\n\
         export const designTokens = {json} as const;\n"
    )
}

fn render_android_theme(tokens: &Tokens) -> Result<String> {
    let mut out = String::new();
    out.push_str("// Auto-generated by design-token-gen. Do not edit manually.\n");
    out.push_str("package com.animus.link.ui\n\n");
    out.push_str("object AnimusTheme {\n");

    for (name, value) in &tokens.colors {
        let color = parse_rgb_u32(value)?;
        out.push_str(
            format!(
                "    const val {}: Long = 0xFF{color:06X}L\n",
                to_android_const_name(name)
            )
            .as_str(),
        );
    }
    out.push('\n');
    for (name, value) in &tokens.radii {
        out.push_str(
            format!(
                "    const val {}: String = \"{}\"\n",
                to_android_const_name(&format!("radius_{name}")),
                escape_kotlin(value)
            )
            .as_str(),
        );
    }
    out.push('\n');
    for (name, value) in sorted_spacing(&tokens.spacing) {
        out.push_str(
            format!(
                "    const val {}: String = \"{}\"\n",
                to_android_const_name(&format!("space_{name}")),
                escape_kotlin(&value)
            )
            .as_str(),
        );
    }
    out.push('\n');
    out.push_str(
        format!(
            "    const val FONT_SANS: String = \"{}\"\n",
            escape_kotlin(&tokens.typography.font_sans)
        )
        .as_str(),
    );
    out.push_str(
        format!(
            "    const val FONT_MONO: String = \"{}\"\n",
            escape_kotlin(&tokens.typography.font_mono)
        )
        .as_str(),
    );
    if let Some(font_metric_mono) = tokens.typography.font_metric_mono.as_deref() {
        out.push_str(
            format!(
                "    const val FONT_METRIC_MONO: String = \"{}\"\n",
                escape_kotlin(font_metric_mono)
            )
            .as_str(),
        );
    }
    out.push_str("}\n");
    Ok(out)
}

fn render_ios_theme(tokens: &Tokens) -> Result<String> {
    let mut out = String::new();
    out.push_str("// Auto-generated by design-token-gen. Do not edit manually.\n");
    out.push_str("import SwiftUI\n\n");
    out.push_str("enum AnimusTheme {\n");
    for (name, value) in &tokens.colors {
        let (r, g, b) = parse_hex_rgb_f32(value)?;
        out.push_str(
            format!(
                "    static let {} = Color(red: {:.6}, green: {:.6}, blue: {:.6})\n",
                to_swift_name(name),
                r,
                g,
                b
            )
            .as_str(),
        );
    }
    out.push('\n');
    for (name, value) in &tokens.radii {
        out.push_str(
            format!(
                "    static let radius{}: String = \"{}\"\n",
                to_swift_suffix(name),
                escape_swift(value)
            )
            .as_str(),
        );
    }
    out.push('\n');
    for (name, value) in sorted_spacing(&tokens.spacing) {
        out.push_str(
            format!(
                "    static let space{}: String = \"{}\"\n",
                to_swift_suffix(&name),
                escape_swift(&value)
            )
            .as_str(),
        );
    }
    out.push('\n');
    out.push_str(
        format!(
            "    static let fontSans: String = \"{}\"\n",
            escape_swift(&tokens.typography.font_sans)
        )
        .as_str(),
    );
    out.push_str(
        format!(
            "    static let fontMono: String = \"{}\"\n",
            escape_swift(&tokens.typography.font_mono)
        )
        .as_str(),
    );
    if let Some(font_metric_mono) = tokens.typography.font_metric_mono.as_deref() {
        out.push_str(
            format!(
                "    static let fontMetricMono: String = \"{}\"\n",
                escape_swift(font_metric_mono)
            )
            .as_str(),
        );
    }
    out.push_str("}\n");
    Ok(out)
}

fn parse_hex_rgb(value: &str) -> Result<u32> {
    let raw = value.trim();
    let raw = raw
        .strip_prefix('#')
        .ok_or_else(|| anyhow!("hex color must start with #, got {raw}"))?;
    if raw.len() != 6 {
        return Err(anyhow!("hex color must be 6 chars, got {value}"));
    }
    u32::from_str_radix(raw, 16).with_context(|| format!("invalid hex color {value}"))
}

fn parse_rgb_u32(value: &str) -> Result<u32> {
    if value.trim_start().starts_with('#') {
        return parse_hex_rgb(value);
    }
    parse_hsl_triplet(value)
}

fn parse_hex_rgb_f32(value: &str) -> Result<(f32, f32, f32)> {
    let rgb = parse_rgb_u32(value)?;
    let r = ((rgb >> 16) & 0xff) as f32 / 255.0;
    let g = ((rgb >> 8) & 0xff) as f32 / 255.0;
    let b = (rgb & 0xff) as f32 / 255.0;
    Ok((r, g, b))
}

fn parse_hsl_triplet(value: &str) -> Result<u32> {
    let parts = value.split_whitespace().collect::<Vec<_>>();
    if parts.len() != 3 {
        return Err(anyhow!(
            "hsl triplet must have 3 parts like '217 68% 3%', got {value}"
        ));
    }
    let h = parts[0]
        .parse::<f32>()
        .with_context(|| format!("invalid H component in {value}"))?;
    let s = parse_percent(parts[1], value)?;
    let l = parse_percent(parts[2], value)?;

    let h = ((h % 360.0) + 360.0) % 360.0;
    let c = (1.0 - (2.0 * l - 1.0).abs()) * s;
    let h_prime = h / 60.0;
    let x = c * (1.0 - ((h_prime % 2.0) - 1.0).abs());

    let (r1, g1, b1) = if (0.0..1.0).contains(&h_prime) {
        (c, x, 0.0)
    } else if (1.0..2.0).contains(&h_prime) {
        (x, c, 0.0)
    } else if (2.0..3.0).contains(&h_prime) {
        (0.0, c, x)
    } else if (3.0..4.0).contains(&h_prime) {
        (0.0, x, c)
    } else if (4.0..5.0).contains(&h_prime) {
        (x, 0.0, c)
    } else {
        (c, 0.0, x)
    };

    let m = l - c / 2.0;
    let r = ((r1 + m) * 255.0).round().clamp(0.0, 255.0) as u32;
    let g = ((g1 + m) * 255.0).round().clamp(0.0, 255.0) as u32;
    let b = ((b1 + m) * 255.0).round().clamp(0.0, 255.0) as u32;

    Ok((r << 16) | (g << 8) | b)
}

fn parse_percent(value: &str, source: &str) -> Result<f32> {
    let raw = value
        .strip_suffix('%')
        .ok_or_else(|| anyhow!("expected percent value in {source}"))?;
    let parsed = raw
        .parse::<f32>()
        .with_context(|| format!("invalid percent component '{value}' in {source}"))?;
    Ok((parsed / 100.0).clamp(0.0, 1.0))
}

fn to_android_const_name(name: &str) -> String {
    name.chars()
        .map(|c| match c {
            '-' | '.' | ' ' => '_',
            _ => c.to_ascii_uppercase(),
        })
        .collect()
}

fn escape_kotlin(value: &str) -> String {
    value.replace('\\', "\\\\").replace('"', "\\\"")
}

fn escape_swift(value: &str) -> String {
    value.replace('\\', "\\\\").replace('"', "\\\"")
}

fn to_swift_name(name: &str) -> String {
    let mut out = String::new();
    let mut upper = false;
    for ch in name.chars() {
        match ch {
            '-' | '_' | '.' | ' ' => upper = true,
            _ => {
                if out.is_empty() {
                    out.push(ch.to_ascii_lowercase());
                } else if upper {
                    out.push(ch.to_ascii_uppercase());
                    upper = false;
                } else {
                    out.push(ch);
                }
            }
        }
    }
    out
}

fn to_swift_suffix(name: &str) -> String {
    let base = to_swift_name(name);
    let mut chars = base.chars();
    let first = match chars.next() {
        Some(ch) => ch,
        None => return String::new(),
    };
    format!(
        "{}{}",
        first.to_ascii_uppercase(),
        chars.collect::<String>()
    )
}

fn sorted_spacing(spacing: &BTreeMap<String, String>) -> Vec<(String, String)> {
    let mut values = spacing
        .iter()
        .map(|(k, v)| (k.clone(), v.clone()))
        .collect::<Vec<_>>();
    values.sort_by(|(a, _), (b, _)| {
        let an = a.parse::<u32>();
        let bn = b.parse::<u32>();
        match (an, bn) {
            (Ok(an), Ok(bn)) => an.cmp(&bn),
            _ => a.cmp(b),
        }
    });
    values
}
